name: login_signup
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+8
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  intl: ^0.18.0
  http: ^0.13.4
  http_parser: ^4.0.2
  fl_chart: ^0.69.0
  flutter_dotenv: ^5.0.2
  image: ^4.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg2.jpg
